/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119348-ge73c59c6c3-20250425"
#endif /* AVUTIL_FFVERSION_H */
